spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      additional-paths:
        - src/main/java
  datasource:
    url: jdbc:sqlite:///Users/lin/IdeaProjects/letsdinner/dinner.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8080
logging:
  config: classpath:log4j2.xml
