spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      additional-paths:
        - src/main/java
  datasource:
    url: jdbc:sqlite://c:/letsdinner/dinner.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8080
logging:
  config: classpath:log4j2.xml
app:
  httpUrl: http://127.0.0.1:8080
  wsUrl: ws://127.0.0.1:8080
